#!/bin/sh
#By Binyuan
module="ssculls"
device="sscull"
mode=664

group="staff"

/sbin/insmod ./$module.ko $*||exit 1

major=$(awk '$2=="'$module'" {print $1}' /proc/devices)

rm -f /dev/${device}
mknod /dev/${device} c $major 0

chgrp $group /dev/${device}
chmod $mode  /dev/${device} 

rm -f /dev/${device}pipe[0-1] 
mknod /dev/${device}pipe0 c $major 1
mknod /dev/${device}pipe1 c $major 2
ln -sf ${device}pipe0 /dev/${device}pipe
chgrp $group /dev/${device}pipe[0-1] 
chmod $mode  /dev/${device}pipe[0-1]

rm -f /dev/${device}single
mknod /dev/${device}single  c $major 3
chgrp $group /dev/${device}single
chmod $mode  /dev/${device}single

rm -f /dev/${device}uid
mknod /dev/${device}uid   c $major 4
chgrp $group /dev/${device}uid
chmod $mode  /dev/${device}uid

rm -f /dev/${device}wuid
mknod /dev/${device}wuid  c $major 5
chgrp $group /dev/${device}wuid
chmod $mode  /dev/${device}wuid

rm -f /dev/${device}priv
mknod /dev/${device}priv  c $major 6
chgrp $group /dev/${device}priv
chmod $mode  /dev/${device}priv

